# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'GMAPS'), (2, 'FACEBOOK'), (3, 'WEBSITE'), (4, 'FOURSQUARE'), (5, 'YELP')])),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitud', models.CharField(max_length=120)),
                ('longitude', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.IntegerField(choices=[(1, 'CREATED'), (2, 'GMAPS_VERIFIED'), (3, 'REAL_VERIFIED'), (4, 'SUSPENDED'), (5, 'REPORTED'), (6, 'DISABLED')], default=1)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='place.Category')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
    ]
