# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('GMAPS', 'GMAPS'), ('FACEBOOK', 'FACEBOOK'), ('WEBSITE', 'WEBSITE'), ('FOURSQUARE', 'FOURSQUARE'), ('YELP', 'YELP')], default='GMAPS', max_length=20),
        ),
    ]
