# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_auto_20160409_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
