# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_auto_20160409_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='rank',
            new_name='score',
        ),
    ]
