# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
