# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'CREATED'), (2, 'GMAPS_VERIFIED'), (3, 'REAL_VERIFIED'), (4, 'SUSPENDED'), (5, 'REPORTED'), (6, 'DISABLED')], default=1, null=True),
        ),
    ]
