# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20160226_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.IntegerField(choices=[(1, 'GMAPS'), (2, 'FACEBOOK'), (3, 'WEBSITE'), (4, 'FOURSQUARE'), (5, 'YELP')]),
        ),
    ]
