# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_remove_link_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='categories',
        ),
        migrations.AddField(
            model_name='place',
            name='has_links',
            field=models.IntegerField(default=0),
        ),
    ]
