# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20160409_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='position',
            new_name='rank',
        ),
    ]
